version: '3'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      LANG: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pk-portal
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: pkportaladmin
      MINIO_ROOT_PASSWORD: pkportaladmin!
      MINIO_DEFAULT_BUCKETS: pkportal-screenshots
      MINIO_REGION_NAME: us-west-2

volumes:
  pgsql_data:
    driver: local
  minio_data:
    driver: local