// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tpportal

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserStatus is an object representing the database table.
type UserStatus struct {
	UserID        int64 `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	StatusID      int64 `boil:"status_id" json:"status_id" toml:"status_id" yaml:"status_id"`
	EducationYear int16 `boil:"education_year" json:"education_year" toml:"education_year" yaml:"education_year"`

	R *userStatusR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userStatusL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserStatusColumns = struct {
	UserID        string
	StatusID      string
	EducationYear string
}{
	UserID:        "user_id",
	StatusID:      "status_id",
	EducationYear: "education_year",
}

var UserStatusTableColumns = struct {
	UserID        string
	StatusID      string
	EducationYear string
}{
	UserID:        "user_statuses.user_id",
	StatusID:      "user_statuses.status_id",
	EducationYear: "user_statuses.education_year",
}

// Generated where

var UserStatusWhere = struct {
	UserID        whereHelperint64
	StatusID      whereHelperint64
	EducationYear whereHelperint16
}{
	UserID:        whereHelperint64{field: "\"user_statuses\".\"user_id\""},
	StatusID:      whereHelperint64{field: "\"user_statuses\".\"status_id\""},
	EducationYear: whereHelperint16{field: "\"user_statuses\".\"education_year\""},
}

// UserStatusRels is where relationship names are stored.
var UserStatusRels = struct {
	Status string
	User   string
}{
	Status: "Status",
	User:   "User",
}

// userStatusR is where relationships are stored.
type userStatusR struct {
	Status *Status `boil:"Status" json:"Status" toml:"Status" yaml:"Status"`
	User   *User   `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userStatusR) NewStruct() *userStatusR {
	return &userStatusR{}
}

func (r *userStatusR) GetStatus() *Status {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *userStatusR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// userStatusL is where Load methods for each relationship are stored.
type userStatusL struct{}

var (
	userStatusAllColumns            = []string{"user_id", "status_id", "education_year"}
	userStatusColumnsWithoutDefault = []string{"user_id", "status_id", "education_year"}
	userStatusColumnsWithDefault    = []string{}
	userStatusPrimaryKeyColumns     = []string{"user_id", "education_year"}
	userStatusGeneratedColumns      = []string{}
)

type (
	// UserStatusSlice is an alias for a slice of pointers to UserStatus.
	// This should almost always be used instead of []UserStatus.
	UserStatusSlice []*UserStatus
	// UserStatusHook is the signature for custom UserStatus hook methods
	UserStatusHook func(context.Context, boil.ContextExecutor, *UserStatus) error

	userStatusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userStatusType                 = reflect.TypeOf(&UserStatus{})
	userStatusMapping              = queries.MakeStructMapping(userStatusType)
	userStatusPrimaryKeyMapping, _ = queries.BindMapping(userStatusType, userStatusMapping, userStatusPrimaryKeyColumns)
	userStatusInsertCacheMut       sync.RWMutex
	userStatusInsertCache          = make(map[string]insertCache)
	userStatusUpdateCacheMut       sync.RWMutex
	userStatusUpdateCache          = make(map[string]updateCache)
	userStatusUpsertCacheMut       sync.RWMutex
	userStatusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userStatusAfterSelectHooks []UserStatusHook

var userStatusBeforeInsertHooks []UserStatusHook
var userStatusAfterInsertHooks []UserStatusHook

var userStatusBeforeUpdateHooks []UserStatusHook
var userStatusAfterUpdateHooks []UserStatusHook

var userStatusBeforeDeleteHooks []UserStatusHook
var userStatusAfterDeleteHooks []UserStatusHook

var userStatusBeforeUpsertHooks []UserStatusHook
var userStatusAfterUpsertHooks []UserStatusHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserStatus) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserStatus) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserStatus) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserStatus) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserStatus) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserStatus) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserStatus) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserStatus) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserStatus) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userStatusAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserStatusHook registers your hook function for all future operations.
func AddUserStatusHook(hookPoint boil.HookPoint, userStatusHook UserStatusHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userStatusAfterSelectHooks = append(userStatusAfterSelectHooks, userStatusHook)
	case boil.BeforeInsertHook:
		userStatusBeforeInsertHooks = append(userStatusBeforeInsertHooks, userStatusHook)
	case boil.AfterInsertHook:
		userStatusAfterInsertHooks = append(userStatusAfterInsertHooks, userStatusHook)
	case boil.BeforeUpdateHook:
		userStatusBeforeUpdateHooks = append(userStatusBeforeUpdateHooks, userStatusHook)
	case boil.AfterUpdateHook:
		userStatusAfterUpdateHooks = append(userStatusAfterUpdateHooks, userStatusHook)
	case boil.BeforeDeleteHook:
		userStatusBeforeDeleteHooks = append(userStatusBeforeDeleteHooks, userStatusHook)
	case boil.AfterDeleteHook:
		userStatusAfterDeleteHooks = append(userStatusAfterDeleteHooks, userStatusHook)
	case boil.BeforeUpsertHook:
		userStatusBeforeUpsertHooks = append(userStatusBeforeUpsertHooks, userStatusHook)
	case boil.AfterUpsertHook:
		userStatusAfterUpsertHooks = append(userStatusAfterUpsertHooks, userStatusHook)
	}
}

// One returns a single userStatus record from the query.
func (q userStatusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserStatus, error) {
	o := &UserStatus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tpportal: failed to execute a one query for user_statuses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserStatus records from the query.
func (q userStatusQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserStatusSlice, error) {
	var o []*UserStatus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "tpportal: failed to assign all query results to UserStatus slice")
	}

	if len(userStatusAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserStatus records in the query.
func (q userStatusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to count user_statuses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userStatusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "tpportal: failed to check if user_statuses exists")
	}

	return count > 0, nil
}

// Status pointed to by the foreign key.
func (o *UserStatus) Status(mods ...qm.QueryMod) statusQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.StatusID),
	}

	queryMods = append(queryMods, mods...)

	return Statuses(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserStatus) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadStatus allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userStatusL) LoadStatus(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserStatus interface{}, mods queries.Applicator) error {
	var slice []*UserStatus
	var object *UserStatus

	if singular {
		var ok bool
		object, ok = maybeUserStatus.(*UserStatus)
		if !ok {
			object = new(UserStatus)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserStatus))
			}
		}
	} else {
		s, ok := maybeUserStatus.(*[]*UserStatus)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserStatus))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userStatusR{}
		}
		args = append(args, object.StatusID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userStatusR{}
			}

			for _, a := range args {
				if a == obj.StatusID {
					continue Outer
				}
			}

			args = append(args, obj.StatusID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`statuses`),
		qm.WhereIn(`statuses.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Status")
	}

	var resultSlice []*Status
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Status")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for statuses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for statuses")
	}

	if len(statusAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Status = foreign
		if foreign.R == nil {
			foreign.R = &statusR{}
		}
		foreign.R.UserStatuses = append(foreign.R.UserStatuses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StatusID == foreign.ID {
				local.R.Status = foreign
				if foreign.R == nil {
					foreign.R = &statusR{}
				}
				foreign.R.UserStatuses = append(foreign.R.UserStatuses, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userStatusL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserStatus interface{}, mods queries.Applicator) error {
	var slice []*UserStatus
	var object *UserStatus

	if singular {
		var ok bool
		object, ok = maybeUserStatus.(*UserStatus)
		if !ok {
			object = new(UserStatus)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserStatus))
			}
		}
	} else {
		s, ok := maybeUserStatus.(*[]*UserStatus)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserStatus))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userStatusR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userStatusR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserStatuses = append(foreign.R.UserStatuses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserStatuses = append(foreign.R.UserStatuses, local)
				break
			}
		}
	}

	return nil
}

// SetStatus of the userStatus to the related item.
// Sets o.R.Status to related.
// Adds o to related.R.UserStatuses.
func (o *UserStatus) SetStatus(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Status) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_statuses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"status_id"}),
		strmangle.WhereClause("\"", "\"", 2, userStatusPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.EducationYear}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StatusID = related.ID
	if o.R == nil {
		o.R = &userStatusR{
			Status: related,
		}
	} else {
		o.R.Status = related
	}

	if related.R == nil {
		related.R = &statusR{
			UserStatuses: UserStatusSlice{o},
		}
	} else {
		related.R.UserStatuses = append(related.R.UserStatuses, o)
	}

	return nil
}

// SetUser of the userStatus to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserStatuses.
func (o *UserStatus) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_statuses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userStatusPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.EducationYear}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userStatusR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserStatuses: UserStatusSlice{o},
		}
	} else {
		related.R.UserStatuses = append(related.R.UserStatuses, o)
	}

	return nil
}

// UserStatuses retrieves all the records using an executor.
func UserStatuses(mods ...qm.QueryMod) userStatusQuery {
	mods = append(mods, qm.From("\"user_statuses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_statuses\".*"})
	}

	return userStatusQuery{q}
}

// FindUserStatus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserStatus(ctx context.Context, exec boil.ContextExecutor, userID int64, educationYear int16, selectCols ...string) (*UserStatus, error) {
	userStatusObj := &UserStatus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_statuses\" where \"user_id\"=$1 AND \"education_year\"=$2", sel,
	)

	q := queries.Raw(query, userID, educationYear)

	err := q.Bind(ctx, exec, userStatusObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "tpportal: unable to select from user_statuses")
	}

	if err = userStatusObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userStatusObj, err
	}

	return userStatusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserStatus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("tpportal: no user_statuses provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userStatusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userStatusInsertCacheMut.RLock()
	cache, cached := userStatusInsertCache[key]
	userStatusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userStatusAllColumns,
			userStatusColumnsWithDefault,
			userStatusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userStatusType, userStatusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userStatusType, userStatusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_statuses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_statuses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "tpportal: unable to insert into user_statuses")
	}

	if !cached {
		userStatusInsertCacheMut.Lock()
		userStatusInsertCache[key] = cache
		userStatusInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserStatus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserStatus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userStatusUpdateCacheMut.RLock()
	cache, cached := userStatusUpdateCache[key]
	userStatusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userStatusAllColumns,
			userStatusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("tpportal: unable to update user_statuses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_statuses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userStatusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userStatusType, userStatusMapping, append(wl, userStatusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update user_statuses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by update for user_statuses")
	}

	if !cached {
		userStatusUpdateCacheMut.Lock()
		userStatusUpdateCache[key] = cache
		userStatusUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userStatusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update all for user_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to retrieve rows affected for user_statuses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserStatusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("tpportal: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_statuses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userStatusPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to update all in userStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to retrieve rows affected all in update all userStatus")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserStatus) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("tpportal: no user_statuses provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userStatusColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userStatusUpsertCacheMut.RLock()
	cache, cached := userStatusUpsertCache[key]
	userStatusUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userStatusAllColumns,
			userStatusColumnsWithDefault,
			userStatusColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userStatusAllColumns,
			userStatusPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("tpportal: unable to upsert user_statuses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userStatusPrimaryKeyColumns))
			copy(conflict, userStatusPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_statuses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userStatusType, userStatusMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userStatusType, userStatusMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "tpportal: unable to upsert user_statuses")
	}

	if !cached {
		userStatusUpsertCacheMut.Lock()
		userStatusUpsertCache[key] = cache
		userStatusUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserStatus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserStatus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("tpportal: no UserStatus provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userStatusPrimaryKeyMapping)
	sql := "DELETE FROM \"user_statuses\" WHERE \"user_id\"=$1 AND \"education_year\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete from user_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by delete for user_statuses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userStatusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("tpportal: no userStatusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete all from user_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by deleteall for user_statuses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserStatusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userStatusBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_statuses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userStatusPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: unable to delete all from userStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "tpportal: failed to get rows affected by deleteall for user_statuses")
	}

	if len(userStatusAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserStatus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserStatus(ctx, exec, o.UserID, o.EducationYear)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserStatusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserStatusSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_statuses\".* FROM \"user_statuses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userStatusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "tpportal: unable to reload all in UserStatusSlice")
	}

	*o = slice

	return nil
}

// UserStatusExists checks if the UserStatus row exists.
func UserStatusExists(ctx context.Context, exec boil.ContextExecutor, userID int64, educationYear int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_statuses\" where \"user_id\"=$1 AND \"education_year\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, educationYear)
	}
	row := exec.QueryRowContext(ctx, sql, userID, educationYear)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "tpportal: unable to check if user_statuses exists")
	}

	return exists, nil
}

// Exists checks if the UserStatus row exists.
func (o *UserStatus) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserStatusExists(ctx, exec, o.UserID, o.EducationYear)
}
